# Generated by Django 5.2 on 2026-03-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('activate', 'activate'), ('draft', 'draft')], default='activate', max_length=10),
        ),
    ]
